apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: routes/its-metrics-d7-dev
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: its-metrics-d7-dev
    name: its-metrics-d7-dev
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: its-metrics-d7-dev
      deploymentconfig: its-metrics-d7-dev
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
